# Generated by Django 4.1.4 on 2022-12-21 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webnotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorModal',
            new_name='Author',
        ),
    ]
